BROADCAST_HOST = ""
BROADCAST_PORT = 50000


PUBLIC_KEY_BROADCAST_PREFIX = "PUBLIC_KEY_BROADCAST_PREFIX#"
COLLECT_PK_LIST_PREFIX = "COLLECT_PK_LIST_PREFIX#"
SYNCHRONIZE_CLOCK_PREFIX = "SYNCHRONIZE_CLOCK_PREFIX#"
MASTER_CLOCK_PREFIX = "MASTER_CLOCK_PREFIX#"
SECURITY_MESSAGE_PREFIX = "SECURITY_MESSAGE_PREFIX#"


MESSAGE_INTERVAL = 10
